version: '3.8'

services:
  app:
    container_name: 'todoapp'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3030:3030
    stdin_open: true
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DBNAME=todo4
      - APP_PORT=3030
    command: npm run prod
volumes:
  node_modules: